services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    healthcheck:
      test: psql -U postgres -q -d postgres -c "SELECT 'ready';"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
#     secrets:
#       - postgres_password
# secrets:
#   postgres_password:
#     environment: "POSTGRES_PASSWORD"
